### ISSUE TITLE
Jquery included in main.js and scope issues

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#154] opened 2016-04-19 11:58 UTC
I've noticed that jQuery is being included in `main.js` and therefore being loaded twice. I haven't tested this in a clean build but I'm pretty sure it's not just in the one I'm working on. I think it's because jQuery is a requirement of Bootstrap, so that's pulling it through.

I've also had to do:
    
    window.$ = window.jQuery = jQuery;

...to get [Slick](http://kenwheeler.github.io/slick/) working.

**Comment by danimalweb** [comment] 2016-04-19 15:48
I'm working on two v1.3 builds and jQuery is not included in my `main.js`. I'm not pulling the entire BS library only a few selected components. I tested including the full Bootstrap and the jQuery library was still not included.

I think this is because we have `var $ = window.jQuery;` at the top of our file. Maybe one of your deps does not use $ and wants the jQuery variable instead? 

Can you remove any extra dependencies in your project and let me know if any of them are including jQuery?

Would this solve it?

var $ = window.jQuery;
var jQuery = window.jQuery;

This might become an ongoing issue was additional deps might be importing jQuery in different ways ($ vs jQuery etc).

**Comment by danimalweb** [comment] 2016-05-15 22:22
Did you get this resolved? Can we close this issue?

**Comment by danimalweb** [comment] 2016-05-19 14:40
Closing for now, unable to reproduce locally. Re-open the next time this happens.

**Closed by danimalweb** 2016-05-19 14:40 UTC
Labels: Javascript
